/** Arabic nationality adjectives for umrah_travellers.nationality.
 *  Excludes إسرائيلي and إيراني. GCC common values listed first. */

const GCC_NATIONALITIES = [
  'بحريني',
  'سعودي',
  'كويتي',
  'إماراتي',
  'قطري',
  'عماني',
] as const

const OTHER_NATIONALITIES = [
  'أذربيجاني',
  'أرجنتيني',
  'أردني',
  'أرميني',
  'أسترالي',
  'إستوني',
  'إسواتيني',
  'أفغاني',
  'ألباني',
  'ألماني',
  'أمريكي',
  'أندوري',
  'إندونيسي',
  'أنغولي',
  'أوروغواي',
  'أوزبكي',
  'أوغندي',
  'أوكراني',
  'أيرلندي',
  'آيسلندي',
  'إثيوبي',
  'إريتري',
  'إسباني',
  'إيطالي',
  'باكستاني',
  'برازيلي',
  'برتغالي',
  'بروني',
  'بلجيكي',
  'بلغاري',
  'بليزي',
  'بنغلاديشي',
  'بنمي',
  'بنيني',
  'بوتسواني',
  'بوروندي',
  'بوركيني',
  'بوسني',
  'بوليفي',
  'بيروفي',
  'تايلندي',
  'تايواني',
  'تركماني',
  'تركي',
  'تشادي',
  'تشيكي',
  'تشيلي',
  'تنزاني',
  'توغولي',
  'تونسي',
  'جزر القمر',
  'جزائري',
  'جنوب أفريقي',
  'جورجي',
  'جيبوتي',
  'دنماركي',
  'دومينيكي',
  'روسي',
  'روماني',
  'زامبي',
  'زيمبابوي',
  'سريلانكي',
  'سلوفاكي',
  'سلوفيني',
  'سنغافوري',
  'سنغالي',
  'سوداني',
  'سوري',
  'سورينامي',
  'سويدي',
  'سويسري',
  'سيراليوني',
  'صربي',
  'صومالي',
  'صيني',
  'طاجيكي',
  'عراقي',
  'غابوني',
  'غامبي',
  'غاني',
  'غواتيمالي',
  'غوياني',
  'غيني',
  'فلبيني',
  'فلسطيني',
  'فنزويلي',
  'فنلندي',
  'فيتنامي',
  'فيجي',
  'قبرصي',
  'قرغيزي',
  'كازاخستاني',
  'كاميروني',
  'كندي',
  'كوري جنوبي',
  'كوري شمالي',
  'كوستاريكي',
  'كولومبي',
  'كونغولي',
  'كوبي',
  'كيني',
  'لاتفي',
  'لاوسي',
  'لبناني',
  'لكسمبورغي',
  'ليبي',
  'ليبيري',
  'ليتواني',
  'مالديفي',
  'مالطي',
  'ماليزي',
  'ماليوي',
  'مالي',
  'مجري',
  'مقدوني',
  'مصري',
  'مغربي',
  'مكسيكي',
  'منغولي',
  'موريتاني',
  'موريشيوسي',
  'موزمبيقي',
  'مولدوفي',
  'ميانماري',
  'ناميبي',
  'نرويجي',
  'نمساوي',
  'نيبالي',
  'نيجيري',
  'نيكاراغوي',
  'نيوزيلندي',
  'هايتي',
  'هندي',
  'هندوراسي',
  'هولندي',
  'يمني',
  'يوناني',
] as const

const EXCLUDED = new Set(['إسرائيلي', 'إيراني'])

const restSorted = [...OTHER_NATIONALITIES]
  .filter(n => !EXCLUDED.has(n) && !(GCC_NATIONALITIES as readonly string[]).includes(n))
  .sort((a, b) => a.localeCompare(b, 'ar'))

/** Ordered list: GCC first, then remaining nationalities alphabetically (ar). */
export const ARABIC_NATIONALITIES: string[] = [
  ...GCC_NATIONALITIES,
  ...restSorted,
].filter(n => !EXCLUDED.has(n))

/** Options for a select, preserving a legacy stored value if not in the list. */
export function nationalitySelectOptions(current?: string | null): string[] {
  const value = (current ?? '').trim()
  if (value && !ARABIC_NATIONALITIES.includes(value)) {
    return [value, ...ARABIC_NATIONALITIES]
  }
  return ARABIC_NATIONALITIES
}
